MvcProjeKampi/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class HeadingController : Controller
    {
        // Önce listeleme işlemi yapmak için

        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm=new WriterManager(new EfWriterDal());
        

        public ActionResult Index()
        {
            var headingvalues = hm.GetList();
            return View(headingvalues);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();

            List<SelectListItem> valuewriter = (from y in wm.GetListe()
                                                select new SelectListItem
                                                {
                                                    Text = y.WriterName + " " + y.WriterSurName,
                                                    Value = y.WriterID.ToString()

                                                }).ToList();

            ViewBag.vlc = valuecategory;
            ViewBag.vlw = valuewriter;
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            hm.HeadingAdd(p);
            return RedirectToAction("Index");
        }

        public ActionResult ContentByHeading()
        {
            return View();
        }
    }
}
//Valuenumber seçmiş olduğum değerin id si
//displaynumber seçmiş olduğum değerin kendisi

MvcProjeKampi/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Başlık Ekleme</h1>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div>
        <div class="form-group">
            @Html.Label("Başlık Adı")
            @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
            <div id="error" style="color:red">@Html.ValidationMessageFor(x => x.HeadingName)</div>

            <br />
            @Html.Label("Kategori")
            @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })


            <br />
            @Html.Label("Yazar")
            @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
            <div id="error" style="color:red">@Html.ValidationMessageFor(x => x.WriterID)</div>
            <br />

            <button class="btn btn-info">Başlık Ekle</button>
        </div>
    </div>
}

MvcProjeKampi/Views/Heading/ContentByHeading.cshtml
@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            <div class="time-label">
                                <span class="bg-success">Tarih</span>
                            </div>
                            <!-- /.timeline-label -->
                            <!-- timeline item -->
                            <div>
                                <i class="fas fa-comment bg-yellow"></i>
                                <div class="timeline-item">
                                    <h3 class="timeline-header"><a href="#">Test</a> Deneme</h3>
                                    <div class="timeline-body">
                                        İçerik
                                    </div>
                                </div>
                            </div>
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProjeKampi/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{ string color = "";}
@*<h2>Index</h2>
    <br />
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Başlık</th>
            <th>Kategori</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.HeadingID</td>
                <td>@item.HeadingName</td>
                <td>@item.Category.CategoryName</td>
            </tr>
        }
    </table>
    <br />
    <a href="/Heading/AddHeading/" class="btn btn-info"> Yeni Başık Ekle </a>*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Projects</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
   
          
    <section class="content">
        <br />
        <!-- Default box -->
        <div class="card">

            <div class="card-header">
                <h3 class="card-title" ">Başlık İşlemleri</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 30%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Tiyatro")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Kitap")
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.CategoryName == "Eğitim")
                            {
                                color = "badge badge-dark";
                            }
                            if (item.Category.CategoryName == "Spor")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Film")
                            {
                                color = "badge badge-pill";
                            }
                            if (item.Category.CategoryName == "Dizi")
                            {
                                color = "badge badge-primary";
                            }
                            if (item.Category.CategoryName == "Sosyal Medya")
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryName == "Teknoloji")
                            {
                                color = "badge badge-light";
                            }
                            <tr>
                                <td>
                                    @item.HeadingID          

                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>

                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="#">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="#">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                        </tbody>
                </table>
            </div>
        </div>

    </section>

       
</body>
</html>
<a href="AddHeading/" class="btn btn-primary">Yeni Başlık Girişi</a>